apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cm-test-role-binding
  namespace: cm-test-ns
subjects:
- kind: ServiceAccount
  name: cm-test-sa
  namespace: cm-test-ns
roleRef:
  kind: Role
  name: cm-test-role
  namespace: cm-test-ns
  apiGroup: rbac.authorization.k8s.io
